// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const getDatasourceUrl = () => {
  if (process.env["DATABASE_URL"]) {
    return process.env["DATABASE_URL"];
  }

  const user = encodeURIComponent(process.env["DB_USER"] || "");
  const password = encodeURIComponent(process.env["DB_PASSWORD"] || "");
  const host = process.env["DB_HOST"] || "localhost";
  const port = process.env["DB_PORT"] || "3306";
  const database = process.env["DB_NAME"] || "";

  return `mysql://${user}:${password}@${host}:${port}/${database}`;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatasourceUrl(),
  },
});
